### ISSUE TITLE
Consider a different package name?

### ISSUE THREAD

**Issue by ViralBShah** [zekeriyasari/Causal.jl#27]
Hi @zekeriyasari, this is a really cool package! @chrisrackauckas pointed it to me. While I'm taking a look, it occurred to me that it perhaps should consider a different name. Specifically, the package guidelines suggest not using `Ju` as a package name prefix.

https://julialang.github.io/Pkg.jl/dev/creating-packages/#Package-naming-guidelines-1

Would you be open to considering a different name? FWIW, I think the current name is not easy to pronounce, and this package has great potential, and a more memorable name might help!

I'm happy to chat on the Julia slack if it helps. Thanks.

**Comment by zekeriyasari** [comment]
Hi @ViralBShah . Thank you so much for your suggestion and kind words. I am very glad that the package succeeded to get the attention of the experts like you and @ChrisRackauckas . 

Since the first release of the package, the most frequent feedback that I get from the Julia community is to rename the package. I see that the name "Jusdl" has not been able not reflect the scope of the package. So, I am definitely open to considering a different name. 

My intension in developing the package is to construct a simulation environment that enables simulation and online data analysis of a wide range of systems. The package should provide the users with the flexibility of enlarging its modelling and analysis scope. It should be user-friendly, especially when it comes to very large scale dynamical systems, providing easy-to-use modelling tools. Keeping in mind all these, the following may be the new names of the package: 

SystemSimulationToolkit
SystemSimulationTools
DynamicalSystemSimulator 
SystemRecipes
InteractingSystems 
ConnectedSystems

I am going to start a thread on the Julia slack and I would very much like to hear your suggestions.

Thank you again for opening this issue.

**Comment by ViralBShah** [comment]
Almost all of those are pretty good. You can also take the route of what Franklin.jl did. Perhaps the discussion in that issue might also give some ideas: https://github.com/tlienart/Franklin.jl/issues/338

**Comment by zekeriyasari** [comment]
>  I feel like SystemRecipes may be more appropriate for a package that uses this one to implement common recipes - so you may want to leave that open.

+1. 

> Perhaps the discussion in that issue might also give some ideas: tlienart/Franklin.jl#338

Very nice discussion with lots of fun. I saw once again finding a good name is very important but not that easy. 

By the way, among ones I listed above "SystemSimulationToolkit" is my favorite as it includes "System" (may be of a wide range), "Simulation" (one of the ultimate purposes of the package) and "Toolkit" (as the package provides a toolkit for the modeling and simulation of systems). So, it is very inclusive.

**Comment by ViralBShah** [comment]
That seems to match the baking of ModellingToolkit.jl. How does this project differ from that?

**Comment by zekeriyasari** [comment]
ModellingToolkit and Jusdl have some similarities. Both of the packages provide the users with a high-level API for modeling and simulating systems. As far as I can see from the docs, **ModellingToolkit** focusses mostly on dynamical systems. It basically provides a high-level interface with DifferentialEquations.jl, etc. for easy prototyping of systems. Eventually, ModellingToolkit compiles the model to be simulated and constructs **one and only one differential equation problem** and solves it in one single shot for the whole simulation time. 

On the other hand, Jusdl considers models as **individual connected components**. Components may be of any type,

* A source, i.e. a generator that generates outputs that are functions of time. 
* A sink that processes the simulation data online (during the simulation). In particular, the sinks can be equipped with user-defined plugins to enlarge the data processing capability of the package. For instance, during the simulation Lyapunov exponents of a dynamical system can be calculated online from the data flowing through the connections. 
* A system, which may be a dynamical system characterized by a differential equation or a static system characterized by a function that relates input and output. 

Most importantly, **Jusdl is capable of simulating models that have components of a different type**. For example, in the model, I can connect an ODE system to an SDE or a DDE system. **I do not have to consider just one differential equation type to represent the whole model**. Because, during the simulation, **all the components evolve independently**, i.e. according to its own mathematical model. The interaction between the components is carried out by the connections that are bound to the input-output ports of the components. 

In consequence, it seems to me that the methodology adopted in modeling and simulating the systems are quite different in ModelingToolkit and Jusdl.

**Comment by ViralBShah** [comment]
I like `SystemSimulationToolkit`. @chrisrackauckas - Do you have any thoughts?

**Comment by ChrisRackauckas** [comment]
>but is there a possibility of code sharing between ModelingToolkit and this project?

Yes there is. I am working on adding a causal interface to MTK, so in theory this project could target that as a means to get auto-parallelism and a few other acceleration goodies.

SystemSimulationToolkit is a good name. 

>Most importantly, Jusdl is capable of simulating models that have components of different types. For example, in the model, I can connect an ODE system to an SDE or a DDE system. I do not have to consider just one differential equation type to represent the whole model. Because, during the simulation, all the components evolve independently, i.e. according to its own mathematical model. The interaction between the components is carried out by the connections that are bound to the input-output ports of the components.

You should be careful with that BTW. It's technically correct but the mathematics is a little hairy. The differentiation between these systems is not about interface but about mathematical regularity. The solution to an SDE is generally not Lipschitz continuous and is only Holder continuous for all alpha<0.5, which means an SDE as input to an ODE is at most Holder continuous 0.5 which means a standard ODE integrator could have order loss and an SDE integrator would be more efficient. Similar for DDEs, a DDE input into an ODE is an ODE with untracked discontinuities which would be slower than treating the full system as a DDE in order to perform discontinuity tracking. However, this is an interesting way to think about the modeling complex systems and I don't think it's a reason to drop any functionality, just know about some of the potential efficiency downsides (I will let you know that with all of these components together you're still guaranteed convergence of order dt^(1/2)).

ModelingToolkit acts at a somewhat different level, since it's more about "here's the model you wrote down, but here's the better numerical representation for numerically computing the output", which is something this library can benefit from down the line of course as we add more features.

**Comment by zekeriyasari** [comment]
@ViralBShah I am grateful for your interest in helping the package attract more attention. SystemSimulationToolkit is my favorite, and will probably the new name of the package. 

@ChrisRackauckas I am grateful for your invaluable comments about the details of the differentiation. 

> You should be careful with that BTW. It's technically correct but the mathematics is a little hairy. 

In the previous comments, I pointed out that one may connect different dynamical systems represented by different differential equations to each other. I think this should be regarded as just a nice "feature" of this package. If desires, one may use this feature, of course being aware of the technical issues you mentioned in detail above. Or, the user can simply choose the other way and model the dynamical systems by a common differential equation. I just provide this feature and leave the rest to the user to make his own choice. However, providing a warning message to let the user know this fact may be more informative.

> Yes there is. I am working on adding a causal interface to MTK, so in theory this project could target that as a means to get auto-parallelism and a few other acceleration goodies.

I am really very happy to hear that. Two of the major goals of this package is to provide handy tools for the construction of large scale complex systems and to simulate those systems as fast as possible. For the first part, I think that the package needs its own special syntax for easy model construction without bothering the user too much about the details. Currently, I am working on this part. A very simple example of what I mean is given by the following example model and the corresponding syntax.


![modelgraph](https://user-images.githubusercontent.com/24751240/83455542-c2339000-a466-11ea-86fe-8ef6af256f87.png)

```julia

using Jusdl

# Describe the model
@defmodel model begin 
    @nodes begin 
        gen1 = SinewaveGenerator(frequency=2.)
        gain1 = Gain()
        adder1 = Adder(signs=(+,+))
        gen2 = SinewaveGenerator(frequency=3.)
        adder2 = Adder(signs=(+,+,-))
        gain2 = Gain()
        writer = Writer() 
        gain3 = Gain()
    end 
    @branches begin 
        gen1[1]     =>      gain1[1]   # There is connection between first output pin of gen1 and the first input pin of `gain`
        gain1[1]    =>      adder1[1]
        adder1[1]   =>      adder2[1]
        gen2[1]     =>      adder1[2]
        gen2[1]     =>      adder2[2]  # There is connection between first output pin of gen2 and the first input pin of `adder2`
        adder2[1]   =>      gain2[1]
        gain2[1]    =>      writer[1]
        gain2[1]    =>      gain3[1]
        gain3[1]    =>      adder2[3]
    end
end

# Simuate model 
simulate!(model)
```

The user just "describes" the model by defining its nodes and branches. Of course, the model above is very simple and this syntax needs to be developed for more complex dynamical systems(such as  a large scale dynamical network with a complex topology.)

For the second part of the problem, I need the effective usage of parallelism. In its current version, the package use parallelism but in green-threads (Task) level. During the simulation, a Task is launched for each component to make the component evolve(evolving steps are reading input, solving a differential equation, computing output, and writing the output to its output port). As the model grows, the time it takes to simulate the model also increases, and for an effective simulation, I have to resort to distributed computing to distribute the computational load to available cores. So it will be great to be able to use auto-parallelism and other acceleration goodies to be provided by MTK. I would very much like to discuss these issues on Gitter or Slack channel of SciML

**Comment by jonniedie** [comment]
Glad to see this is getting a rename! It's a cool package and I know a lot of people (myself included) have been looking forward to see someone build a Simulink-like modeling language on top of DifferentialEquations.jl. Since Slack is impermanent, I'll repeat what I said there here with a few extra comments:

I don’t think it should have “Tools” or “Toolbox” in the name. When I see the name “Tools” on a package, I assume that I can grab a few functions or types from it and use them in my existing code. I think ModelingToolkit.jl is a bit of an exception because it can be used either as a full DSL or a take-what-you-need library. When I hear “SystemSimulationTools”, it sounds like a few helper functions that I can use to make simulating systems easier. This, on the other hand, is a full domain-specific language. So I’d call it something that reflects this.

And I don’t think DSLs should necessarily follow the typical Julia package name convention of having full descriptive names (and most don’t: Turing, JuMP, Soss, etc.) Something catchy that maybe hints at it being a simulation modeling package would probably be ideal. A lot of simulation modeling DSLs have "sim" or "mod" in the name (Simulink, Modelica, etc.), so that might be something worth considering (although certainly not required). I think Simulink is a good example because the "link" describes how you connect blocks together in the GUI.

**Comment by Cysor** [comment]
I think @jonniedie makes a good point. What about something like: _`Simodjula`_ ?
Could have it as a standalone name, or as a shortening of something like, **SI**mulation and **MOD**eling in the **JU**lia **LA**nguage.
The name also sounds like modular which relates to the modular nature of using nodes.

**Comment by zekeriyasari** [comment]
`Simodjula` sounds good :) Clear and understandable. 

By the way, I also do think that @jonniedie is definitely right:

> Something catchy that maybe hints at it being a simulation modeling package would probably be ideal

The package should not have a full descriptive name, but instead a short memorable, inclusive name. I came across a suggestion in the [survey ](https://docs.google.com/forms/d/e/1FAIpQLSf6sbG4cjEwG19uTdYEGS41gjI9A762Z3KVEp7E4S-crvo0dg/viewform?vc=0&c=0&w=1)I opened for my talk in JuliaCon. How about `JuST` (Julia Simulation Toolkit)? Sounds really cool. May also be `Just`. 

One other suggestion was `SigFlowLink`. Recalls me `Simulink`.

**Comment by ViralBShah** [comment]
Simodjula is not easy to pronounce or remember the spelling of, imo. I would also suggest to avoid similar names to trademarked names.

I like JuST, but good to consider names that don't have Julia in expansion or even simulation. Example - Franklin.jl, Catalyst.jl etc. What makes this package different from other similar softwares out there?

**Comment by Cysor** [comment]
You make a good point with the spelling, I hadn't really thought about that. I do like the idea of something like Catalyst.jl where the name is a subtle hint to the purpose of the package.

**Comment by zekeriyasari** [comment]
I can see the reasoning behind `Catalyst.jl` as it is a "catalyst for biochemical computations". Definitely a great name for a package. 

But, I must admit that I cannot see the reasoning behind `Franklin.jl`. I cannot see the relation between a chemist and a static site generator package. I would expect the name of a scientist who has something in common with the scope of the package. Sorry for my blindness, but I really wonder where the name Franklin comes from even if I read all the posts https://github.com/tlienart/Franklin.jl/issues/338.

**Comment by ViralBShah** [comment]
Franklin does not have a clear explanation for its name - except that it is just a good name. @tlienart may be able to say a bit about why he picked it. @stefankarpinski offered a reason https://github.com/tlienart/Franklin.jl/issues/338#issuecomment-573787757.

Catalyst.jl naming discussion here: https://github.com/SciML/Catalyst.jl/issues/196
DiffEqFlux here (not much there yet): https://github.com/SciML/DiffEqFlux.jl/issues/354

**Comment by ViralBShah** [comment]
This one is a must read - Stephen Wolfram describes how the name Mathematica came about: https://blog.wolfram.com/2011/10/06/steve-jobs-a-few-memories/

> I’d actually considered that name, but rejected it. I asked Steve why he thought it was good, and he told me his theory for a name was to start from the generic term for something, then romanticize it. His favorite example at the time was Sony’s Trinitron. Well, it went back and forth for a while. But in the end I agreed that, yes, Mathematica was a good name. And so it has been now for nearly 24 years.

**Comment by zekeriyasari** [comment]
I liked the part "start from the generic term for something, then romanticize it"  :)

**Comment by Cysor** [comment]
Correct me if I'm wrong, but would it be fair to say this package essentially enables flow-based programming for Julia? If so, what about something like `Flow.jl` ?

**Comment by zekeriyasari** [comment]
I think your suggestion is great @Cysor. It directly emphasizes the fact that data processed by the components flows through the connections of the model. 

As I did not know much about the concept, I had a look at the Wikipedia article and realized that there is a direct relationship between the definitions of flow-based programming that I take from Wikipedia and the approaches used in the package.
 
> In computer programming, flow-based programming (FBP) is a programming paradigm that defines applications as networks of "black box" processes, which exchange data across predefined connections by message passing, where the connections are specified externally to the processes. 

The package defines models as networks of components which exchange data across connections that that are bound the ports of the components.

> It views an application, not as a single, sequential process, which starts at a point in time, and then does one thing at a time until it is finished, but as a network of asynchronous processes communicating by means of streams of structured data chunks, called "information packets" (IPs)

The package views the model to be simulated not a single lumped component but as a network of different type of components communicating by means of connections. The sampled data flows through these connections.

> The processes communicate by means of fixed-capacity connections. A connection is attached to a process by means of a port

The components communicate by each other by means of fixed capacity(fixed number links) connections which are bound to the input/output ports of the components.

> The network definition is usually diagrammatic and is converted into a connection list in some lower-level language or notation. FBP is often a visual programming language at this level. 

The models can be visualized by block diagrams and associated with a corresponding signal flow diagram. 

By the way, I could not any Julia package named `Flow.jl` in JuliaHub. I really liked `Flow.jl`.

**Comment by ViralBShah** [comment]
So, like Steve Jobs suggested, can we romanticize Flow then into a name, that you could in the future have a domain name for? Flow is nice, but too generic in the google world. Flow itself has hits like - https://www.flowsoftware.com/

**Comment by ViralBShah** [comment]
Random ideas coming into my mind:

FlowFast
Flowing
FlowAlong
Flower

**Comment by zekeriyasari** [comment]
- Flowing
- FlowAlong
- Flower :smile: (the plant ) 
sounds goods. 

How about SignalFlower? The modeling approach adopted in the package is called signal-flow.

**Comment by jonniedie** [comment]
I kinda like SignalFlow, but it turns out there is a programming language called that already?

**Comment by ViralBShah** [comment]
Yeah SignalFlow is a thing: https://developers.signalfx.com/signalflow_analytics/signalflow_overview.html

**Comment by ViralBShah** [comment]
AutoFlow?

**Comment by zekeriyasari** [comment]
How about LetFlow or LetThemFlow like "let the data flow". May be a little informal though :smile:

**Comment by ViralBShah** [comment]
Yeah, those sound a little informal. FlowNet would lead people to think that these are neural networks. AutoFlow by comparison, I think has much less of a neural network connotation.

**Comment by Cysor** [comment]
My concern with AutoFlow is what the Auto would be in reference to?

Here are a few wacky ideas that aren't related to the Flow name, but have subtle links to the packages purpose/operating structure, these might spark some other ideas:
Conduit
[Estuary](https://en.wikipedia.org/wiki/Estuary)
Highway/Roadway
[Backhaul](https://en.wikipedia.org/wiki/Backhaul_(telecommunications))

**Comment by ViralBShah** [comment]
I like the idea of an application driven metaphor, but using it by itself would suggest it is a domain specific package in telecommunications or road networks.
